services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adil-traits
    restart: always
    working_dir: /var/www/html
    ports:
      - 8007:80
    volumes:
      - ../:/var/www/html